name="nit-markplace"
version="1.0.0"
port=8081
ip="0.0.0.0"

[mongo]
ip="47.97.249.37"
port=27017
username="admin"
db_name="nit-markplace-data"
uri="mongodb://47.97.249.37:27017/"
password="0503qwm"

[redis]
ip="47.97.249.37"
port=6379
username=""
password="123ttk"

